# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    cmds:
      - echo "Levantando Servidor..."
      - go run ./cmd/printer-daemon